/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 09 23:58:32 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Stack;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Stack_ESTest extends Stack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push((-1));
      stack0.push((-1));
      int int0 = stack0.top();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(10);
      int int0 = stack0.top();
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(0);
      stack0.push((-1305));
      stack0.pop();
      stack0.push((-1305));
      stack0.push(551918);
      stack0.pop();
      stack0.pop();
      stack0.pop();
      stack0.push(0);
      stack0.pop();
      // Undeclared exception!
      try { 
        stack0.top();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot pop from empty stack
         //
         verifyException("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(0);
      int int0 = stack0.top();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Stack stack0 = new Stack();
      // Undeclared exception!
      try { 
        stack0.pop();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot pop from empty stack
         //
         verifyException("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Stack stack0 = new Stack();
      // Undeclared exception!
      try { 
        stack0.push(61395);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 12
         //
         verifyException("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      stack0.push((-1157));
      // Undeclared exception!
      try { 
        stack0.push((-1157));
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot add to full stack
         //
         verifyException("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(11235);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Stack stack0 = new Stack();
      stack0.push(551928);
      int int0 = stack0.pop();
      assertEquals(551928, int0);
  }
}
